/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const SubscriptionView = IDL.Record({
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'status' : SubscriptionStatus,
  'expiresAt' : Timestamp,
  'stripeSubscriptionId' : IDL.Text,
  'userId' : UserId,
  'stripeCustomerId' : IDL.Text,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'renewalDate' : Timestamp,
  'startDate' : Timestamp,
});
export const RazorpayOrderResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const AdminUserView = IDL.Record({
  'lastLoginAt' : Timestamp,
  'userId' : UserId,
  'lastActiveAt' : Timestamp,
  'subscriptionPlan' : IDL.Text,
  'coursesCompleted' : IDL.Nat,
  'loginCount' : IDL.Nat,
  'subscriptionStatus' : IDL.Text,
  'signupAt' : Timestamp,
  'userIdText' : IDL.Text,
  'totalProgress' : IDL.Float64,
});
export const CapstoneSubscriptionView = IDL.Record({
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'activated' : IDL.Bool,
  'activatedAt' : Timestamp,
  'userId' : UserId,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
});
export const CertificateView = IDL.Record({
  'id' : IDL.Text,
  'verificationCode' : IDL.Text,
  'userId' : UserId,
  'issuedAt' : Timestamp,
  'courseName' : IDL.Text,
  'courseId' : IDL.Text,
});
export const CourseCompletion = IDL.Record({
  'completedAt' : Timestamp,
  'userId' : UserId,
  'certificateId' : IDL.Text,
  'userIdText' : IDL.Text,
  'courseId' : IDL.Text,
});
export const LoginEvent = IDL.Record({
  'userId' : UserId,
  'timestamp' : Timestamp,
  'userIdText' : IDL.Text,
});
export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
});
export const ModuleCategory = IDL.Variant({
  'dsa' : IDL.Null,
  'sql' : IDL.Null,
  'aiml' : IDL.Null,
  'java' : IDL.Null,
  'cloud' : IDL.Null,
  'mncplatforms' : IDL.Null,
  'htmlcss' : IDL.Null,
  'capstonePproject' : IDL.Null,
  'shellscripting' : IDL.Null,
  'networking' : IDL.Null,
  'trending' : IDL.Null,
  'devops' : IDL.Null,
  'hardware' : IDL.Null,
  'excel' : IDL.Null,
  'corporateskills' : IDL.Null,
  'itSupport' : IDL.Null,
  'cybersecurity' : IDL.Null,
  'software' : IDL.Null,
  'etltools' : IDL.Null,
  'cloudaws' : IDL.Null,
  'presentation' : IDL.Null,
  'python' : IDL.Null,
  'corporateWorld' : IDL.Null,
  'machinelearning' : IDL.Null,
  'github' : IDL.Null,
  'itfundamentals' : IDL.Null,
});
export const ITModule = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'isComingSoon' : IDL.Bool,
  'topics' : IDL.Vec(IDL.Text),
  'estimatedHours' : IDL.Nat,
  'category' : ModuleCategory,
  'estimatedMinutes' : IDL.Nat,
});
export const ModuleProgress = IDL.Record({
  'moduleId' : IDL.Nat,
  'completedAt' : IDL.Opt(Timestamp),
  'completed' : IDL.Bool,
});
export const UserProgress = IDL.Record({
  'lastQuizScore' : IDL.Opt(IDL.Nat),
  'userId' : UserId,
  'streakDays' : IDL.Nat,
  'moduleProgress' : IDL.Vec(ModuleProgress),
  'lastQuizAttemptedAt' : IDL.Opt(Timestamp),
  'totalLearningHours' : IDL.Nat,
});
export const QuizAttempt = IDL.Record({
  'userId' : UserId,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'attemptedAt' : Timestamp,
});
export const PaymentRecord = IDL.Record({
  'status' : IDL.Text,
  'userId' : UserId,
  'plan' : IDL.Text,
  'orderId' : IDL.Text,
  'paymentId' : IDL.Text,
  'timestamp' : Timestamp,
  'userIdText' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SubscriptionStats = IDL.Record({
  'recentSignups' : IDL.Nat,
  'totalPayments' : IDL.Nat,
  'subscribedUsers' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'activeSubscriptions' : IDL.Nat,
});
export const GlossaryCategory = IDL.Variant({
  'aiml' : IDL.Null,
  'cloud' : IDL.Null,
  'networking' : IDL.Null,
  'hardware' : IDL.Null,
  'itSupport' : IDL.Null,
  'cybersecurity' : IDL.Null,
  'software' : IDL.Null,
  'general' : IDL.Null,
});
export const Term = IDL.Record({
  'id' : IDL.Nat,
  'term' : IDL.Text,
  'example' : IDL.Text,
  'category' : GlossaryCategory,
  'definition' : IDL.Text,
});
export const StripeWebhookPayload = IDL.Record({
  'stripeSubscriptionId' : IDL.Text,
  'userId' : IDL.Opt(UserId),
  'stripeCustomerId' : IDL.Text,
  'eventType' : IDL.Text,
});
export const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'correctOptionId' : IDL.Nat,
  'question' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});

export const idlService = IDL.Service({
  'activateCapstoneWithRazorpay' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'activateSubscriptionWithRazorpay' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'canAccessCapstone' : IDL.Func([], [IDL.Bool], []),
  'canAccessLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'canAccessModule' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'checkSubscription' : IDL.Func([], [IDL.Opt(SubscriptionView)], []),
  'createCapstoneOrder' : IDL.Func([], [RazorpayOrderResult], []),
  'createRazorpayOrder' : IDL.Func([], [RazorpayOrderResult], []),
  'getAllUsersAdmin' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
  'getCapstoneSubscription' : IDL.Func(
      [],
      [IDL.Opt(CapstoneSubscriptionView)],
      [],
    ),
  'getCertificate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CertificateView)],
      ['query'],
    ),
  'getCourseCompletions' : IDL.Func([], [IDL.Vec(CourseCompletion)], ['query']),
  'getLoginEvents' : IDL.Func([], [IDL.Vec(LoginEvent)], ['query']),
  'getModule' : IDL.Func([IDL.Nat], [IDL.Opt(ITModule)], ['query']),
  'getMyCertificates' : IDL.Func([], [IDL.Vec(CertificateView)], ['query']),
  'getMyProgress' : IDL.Func([], [UserProgress], ['query']),
  'getMyQuizAttempt' : IDL.Func([], [IDL.Opt(QuizAttempt)], ['query']),
  'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getSubscriptionStatsAdmin' : IDL.Func([], [SubscriptionStats], ['query']),
  'getTerm' : IDL.Func([IDL.Nat], [IDL.Opt(Term)], ['query']),
  'getTermsByCategory' : IDL.Func(
      [GlossaryCategory],
      [IDL.Vec(Term)],
      ['query'],
    ),
  'getUserProgressAdmin' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProgress)],
      ['query'],
    ),
  'handleStripeWebhook' : IDL.Func([StripeWebhookPayload], [IDL.Bool], []),
  'linkStripeCustomer' : IDL.Func([IDL.Text], [], []),
  'listGlossaryTerms' : IDL.Func([], [IDL.Vec(Term)], ['query']),
  'listModules' : IDL.Func([], [IDL.Vec(ITModule)], ['query']),
  'listQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'listSubscribers' : IDL.Func([], [IDL.Vec(SubscriptionView)], ['query']),
  'markCourseComplete' : IDL.Func([IDL.Text, IDL.Text], [CertificateView], []),
  'markModuleCompleted' : IDL.Func([IDL.Nat], [], []),
  'recordLoginEvent' : IDL.Func([], [], []),
  'searchGlossary' : IDL.Func([IDL.Text], [IDL.Vec(Term)], ['query']),
  'setOwner' : IDL.Func([], [], []),
  'setRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitQuizAttempt' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [QuizAttempt],
      [],
    ),
  'updateLearningHours' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const SubscriptionView = IDL.Record({
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'status' : SubscriptionStatus,
    'expiresAt' : Timestamp,
    'stripeSubscriptionId' : IDL.Text,
    'userId' : UserId,
    'stripeCustomerId' : IDL.Text,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'renewalDate' : Timestamp,
    'startDate' : Timestamp,
  });
  const RazorpayOrderResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const AdminUserView = IDL.Record({
    'lastLoginAt' : Timestamp,
    'userId' : UserId,
    'lastActiveAt' : Timestamp,
    'subscriptionPlan' : IDL.Text,
    'coursesCompleted' : IDL.Nat,
    'loginCount' : IDL.Nat,
    'subscriptionStatus' : IDL.Text,
    'signupAt' : Timestamp,
    'userIdText' : IDL.Text,
    'totalProgress' : IDL.Float64,
  });
  const CapstoneSubscriptionView = IDL.Record({
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'activated' : IDL.Bool,
    'activatedAt' : Timestamp,
    'userId' : UserId,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
  });
  const CertificateView = IDL.Record({
    'id' : IDL.Text,
    'verificationCode' : IDL.Text,
    'userId' : UserId,
    'issuedAt' : Timestamp,
    'courseName' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const CourseCompletion = IDL.Record({
    'completedAt' : Timestamp,
    'userId' : UserId,
    'certificateId' : IDL.Text,
    'userIdText' : IDL.Text,
    'courseId' : IDL.Text,
  });
  const LoginEvent = IDL.Record({
    'userId' : UserId,
    'timestamp' : Timestamp,
    'userIdText' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
  });
  const ModuleCategory = IDL.Variant({
    'dsa' : IDL.Null,
    'sql' : IDL.Null,
    'aiml' : IDL.Null,
    'java' : IDL.Null,
    'cloud' : IDL.Null,
    'mncplatforms' : IDL.Null,
    'htmlcss' : IDL.Null,
    'capstonePproject' : IDL.Null,
    'shellscripting' : IDL.Null,
    'networking' : IDL.Null,
    'trending' : IDL.Null,
    'devops' : IDL.Null,
    'hardware' : IDL.Null,
    'excel' : IDL.Null,
    'corporateskills' : IDL.Null,
    'itSupport' : IDL.Null,
    'cybersecurity' : IDL.Null,
    'software' : IDL.Null,
    'etltools' : IDL.Null,
    'cloudaws' : IDL.Null,
    'presentation' : IDL.Null,
    'python' : IDL.Null,
    'corporateWorld' : IDL.Null,
    'machinelearning' : IDL.Null,
    'github' : IDL.Null,
    'itfundamentals' : IDL.Null,
  });
  const ITModule = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'isComingSoon' : IDL.Bool,
    'topics' : IDL.Vec(IDL.Text),
    'estimatedHours' : IDL.Nat,
    'category' : ModuleCategory,
    'estimatedMinutes' : IDL.Nat,
  });
  const ModuleProgress = IDL.Record({
    'moduleId' : IDL.Nat,
    'completedAt' : IDL.Opt(Timestamp),
    'completed' : IDL.Bool,
  });
  const UserProgress = IDL.Record({
    'lastQuizScore' : IDL.Opt(IDL.Nat),
    'userId' : UserId,
    'streakDays' : IDL.Nat,
    'moduleProgress' : IDL.Vec(ModuleProgress),
    'lastQuizAttemptedAt' : IDL.Opt(Timestamp),
    'totalLearningHours' : IDL.Nat,
  });
  const QuizAttempt = IDL.Record({
    'userId' : UserId,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'attemptedAt' : Timestamp,
  });
  const PaymentRecord = IDL.Record({
    'status' : IDL.Text,
    'userId' : UserId,
    'plan' : IDL.Text,
    'orderId' : IDL.Text,
    'paymentId' : IDL.Text,
    'timestamp' : Timestamp,
    'userIdText' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SubscriptionStats = IDL.Record({
    'recentSignups' : IDL.Nat,
    'totalPayments' : IDL.Nat,
    'subscribedUsers' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'activeSubscriptions' : IDL.Nat,
  });
  const GlossaryCategory = IDL.Variant({
    'aiml' : IDL.Null,
    'cloud' : IDL.Null,
    'networking' : IDL.Null,
    'hardware' : IDL.Null,
    'itSupport' : IDL.Null,
    'cybersecurity' : IDL.Null,
    'software' : IDL.Null,
    'general' : IDL.Null,
  });
  const Term = IDL.Record({
    'id' : IDL.Nat,
    'term' : IDL.Text,
    'example' : IDL.Text,
    'category' : GlossaryCategory,
    'definition' : IDL.Text,
  });
  const StripeWebhookPayload = IDL.Record({
    'stripeSubscriptionId' : IDL.Text,
    'userId' : IDL.Opt(UserId),
    'stripeCustomerId' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'correctOptionId' : IDL.Nat,
    'question' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  
  return IDL.Service({
    'activateCapstoneWithRazorpay' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'activateSubscriptionWithRazorpay' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'canAccessCapstone' : IDL.Func([], [IDL.Bool], []),
    'canAccessLesson' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'canAccessModule' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'checkSubscription' : IDL.Func([], [IDL.Opt(SubscriptionView)], []),
    'createCapstoneOrder' : IDL.Func([], [RazorpayOrderResult], []),
    'createRazorpayOrder' : IDL.Func([], [RazorpayOrderResult], []),
    'getAllUsersAdmin' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
    'getCapstoneSubscription' : IDL.Func(
        [],
        [IDL.Opt(CapstoneSubscriptionView)],
        [],
      ),
    'getCertificate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CertificateView)],
        ['query'],
      ),
    'getCourseCompletions' : IDL.Func(
        [],
        [IDL.Vec(CourseCompletion)],
        ['query'],
      ),
    'getLoginEvents' : IDL.Func([], [IDL.Vec(LoginEvent)], ['query']),
    'getModule' : IDL.Func([IDL.Nat], [IDL.Opt(ITModule)], ['query']),
    'getMyCertificates' : IDL.Func([], [IDL.Vec(CertificateView)], ['query']),
    'getMyProgress' : IDL.Func([], [UserProgress], ['query']),
    'getMyQuizAttempt' : IDL.Func([], [IDL.Opt(QuizAttempt)], ['query']),
    'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getSubscriptionStatsAdmin' : IDL.Func([], [SubscriptionStats], ['query']),
    'getTerm' : IDL.Func([IDL.Nat], [IDL.Opt(Term)], ['query']),
    'getTermsByCategory' : IDL.Func(
        [GlossaryCategory],
        [IDL.Vec(Term)],
        ['query'],
      ),
    'getUserProgressAdmin' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProgress)],
        ['query'],
      ),
    'handleStripeWebhook' : IDL.Func([StripeWebhookPayload], [IDL.Bool], []),
    'linkStripeCustomer' : IDL.Func([IDL.Text], [], []),
    'listGlossaryTerms' : IDL.Func([], [IDL.Vec(Term)], ['query']),
    'listModules' : IDL.Func([], [IDL.Vec(ITModule)], ['query']),
    'listQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'listSubscribers' : IDL.Func([], [IDL.Vec(SubscriptionView)], ['query']),
    'markCourseComplete' : IDL.Func(
        [IDL.Text, IDL.Text],
        [CertificateView],
        [],
      ),
    'markModuleCompleted' : IDL.Func([IDL.Nat], [], []),
    'recordLoginEvent' : IDL.Func([], [], []),
    'searchGlossary' : IDL.Func([IDL.Text], [IDL.Vec(Term)], ['query']),
    'setOwner' : IDL.Func([], [], []),
    'setRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitQuizAttempt' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [QuizAttempt],
        [],
      ),
    'updateLearningHours' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };