/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserView {
  'lastLoginAt' : Timestamp,
  'userId' : UserId,
  'lastActiveAt' : Timestamp,
  'subscriptionPlan' : string,
  'coursesCompleted' : bigint,
  'loginCount' : bigint,
  'subscriptionStatus' : string,
  'signupAt' : Timestamp,
  'userIdText' : string,
  'totalProgress' : number,
}
export interface CapstoneSubscriptionView {
  'razorpayPaymentId' : [] | [string],
  'activated' : boolean,
  'activatedAt' : Timestamp,
  'userId' : UserId,
  'razorpayOrderId' : [] | [string],
}
export interface CertificateView {
  'id' : string,
  'verificationCode' : string,
  'userId' : UserId,
  'issuedAt' : Timestamp,
  'courseName' : string,
  'courseId' : string,
}
export interface CourseCompletion {
  'completedAt' : Timestamp,
  'userId' : UserId,
  'certificateId' : string,
  'userIdText' : string,
  'courseId' : string,
}
export type GlossaryCategory = { 'aiml' : null } |
  { 'cloud' : null } |
  { 'networking' : null } |
  { 'hardware' : null } |
  { 'itSupport' : null } |
  { 'cybersecurity' : null } |
  { 'software' : null } |
  { 'general' : null };
export interface ITModule {
  'id' : bigint,
  'title' : string,
  'difficulty' : string,
  'description' : string,
  'lessons' : Array<Lesson>,
  'isComingSoon' : boolean,
  'topics' : Array<string>,
  'estimatedHours' : bigint,
  'category' : ModuleCategory,
  'estimatedMinutes' : bigint,
}
export interface Lesson {
  'title' : string,
  'description' : string,
  'durationMinutes' : bigint,
}
export interface LoginEvent {
  'userId' : UserId,
  'timestamp' : Timestamp,
  'userIdText' : string,
}
export type ModuleCategory = { 'dsa' : null } |
  { 'sql' : null } |
  { 'aiml' : null } |
  { 'java' : null } |
  { 'cloud' : null } |
  { 'mncplatforms' : null } |
  { 'htmlcss' : null } |
  { 'capstonePproject' : null } |
  { 'shellscripting' : null } |
  { 'networking' : null } |
  { 'trending' : null } |
  { 'devops' : null } |
  { 'hardware' : null } |
  { 'excel' : null } |
  { 'corporateskills' : null } |
  { 'itSupport' : null } |
  { 'cybersecurity' : null } |
  { 'software' : null } |
  { 'etltools' : null } |
  { 'cloudaws' : null } |
  { 'presentation' : null } |
  { 'python' : null } |
  { 'corporateWorld' : null } |
  { 'machinelearning' : null } |
  { 'github' : null } |
  { 'itfundamentals' : null };
export interface ModuleProgress {
  'moduleId' : bigint,
  'completedAt' : [] | [Timestamp],
  'completed' : boolean,
}
export interface PaymentRecord {
  'status' : string,
  'userId' : UserId,
  'plan' : string,
  'orderId' : string,
  'paymentId' : string,
  'timestamp' : Timestamp,
  'userIdText' : string,
  'amount' : bigint,
}
export interface QuizAttempt {
  'userId' : UserId,
  'score' : bigint,
  'totalQuestions' : bigint,
  'attemptedAt' : Timestamp,
}
export interface QuizOption { 'id' : bigint, 'text' : string }
export interface QuizQuestion {
  'id' : bigint,
  'correctOptionId' : bigint,
  'question' : string,
  'options' : Array<QuizOption>,
}
export type RazorpayOrderResult = { 'ok' : string } |
  { 'err' : string };
export interface StripeWebhookPayload {
  'stripeSubscriptionId' : string,
  'userId' : [] | [UserId],
  'stripeCustomerId' : string,
  'eventType' : string,
}
export interface SubscriptionStats {
  'recentSignups' : bigint,
  'totalPayments' : bigint,
  'subscribedUsers' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'activeSubscriptions' : bigint,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'inactive' : null };
export interface SubscriptionView {
  'razorpayPaymentId' : [] | [string],
  'status' : SubscriptionStatus,
  'expiresAt' : Timestamp,
  'stripeSubscriptionId' : string,
  'userId' : UserId,
  'stripeCustomerId' : string,
  'razorpayOrderId' : [] | [string],
  'renewalDate' : Timestamp,
  'startDate' : Timestamp,
}
export interface Term {
  'id' : bigint,
  'term' : string,
  'example' : string,
  'category' : GlossaryCategory,
  'definition' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProgress {
  'lastQuizScore' : [] | [bigint],
  'userId' : UserId,
  'streakDays' : bigint,
  'moduleProgress' : Array<ModuleProgress>,
  'lastQuizAttemptedAt' : [] | [Timestamp],
  'totalLearningHours' : bigint,
}
export interface _SERVICE {
  'activateCapstoneWithRazorpay' : ActorMethod<[string, string], boolean>,
  'activateSubscriptionWithRazorpay' : ActorMethod<[string, string], boolean>,
  'canAccessCapstone' : ActorMethod<[], boolean>,
  'canAccessLesson' : ActorMethod<[bigint], boolean>,
  'canAccessModule' : ActorMethod<[bigint], boolean>,
  'checkSubscription' : ActorMethod<[], [] | [SubscriptionView]>,
  'createCapstoneOrder' : ActorMethod<[], RazorpayOrderResult>,
  'createRazorpayOrder' : ActorMethod<[], RazorpayOrderResult>,
  'getAllUsersAdmin' : ActorMethod<[], Array<AdminUserView>>,
  'getCapstoneSubscription' : ActorMethod<[], [] | [CapstoneSubscriptionView]>,
  'getCertificate' : ActorMethod<[string], [] | [CertificateView]>,
  'getCourseCompletions' : ActorMethod<[], Array<CourseCompletion>>,
  'getLoginEvents' : ActorMethod<[], Array<LoginEvent>>,
  'getModule' : ActorMethod<[bigint], [] | [ITModule]>,
  'getMyCertificates' : ActorMethod<[], Array<CertificateView>>,
  'getMyProgress' : ActorMethod<[], UserProgress>,
  'getMyQuizAttempt' : ActorMethod<[], [] | [QuizAttempt]>,
  'getPaymentRecords' : ActorMethod<[], Array<PaymentRecord>>,
  'getSubscriptionStatsAdmin' : ActorMethod<[], SubscriptionStats>,
  'getTerm' : ActorMethod<[bigint], [] | [Term]>,
  'getTermsByCategory' : ActorMethod<[GlossaryCategory], Array<Term>>,
  'getUserProgressAdmin' : ActorMethod<[UserId], [] | [UserProgress]>,
  'handleStripeWebhook' : ActorMethod<[StripeWebhookPayload], boolean>,
  'linkStripeCustomer' : ActorMethod<[string], undefined>,
  'listGlossaryTerms' : ActorMethod<[], Array<Term>>,
  'listModules' : ActorMethod<[], Array<ITModule>>,
  'listQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'listSubscribers' : ActorMethod<[], Array<SubscriptionView>>,
  'markCourseComplete' : ActorMethod<[string, string], CertificateView>,
  'markModuleCompleted' : ActorMethod<[bigint], undefined>,
  'recordLoginEvent' : ActorMethod<[], undefined>,
  'searchGlossary' : ActorMethod<[string], Array<Term>>,
  'setOwner' : ActorMethod<[], undefined>,
  'setRazorpayKeys' : ActorMethod<[string, string], boolean>,
  'submitQuizAttempt' : ActorMethod<[Array<[bigint, bigint]>], QuizAttempt>,
  'updateLearningHours' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];