/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StripeWebhookPayload {
    stripeSubscriptionId: string;
    userId?: UserId;
    stripeCustomerId: string;
    eventType: string;
}
export type Timestamp = bigint;
export interface SubscriptionView {
    razorpayPaymentId?: string;
    status: SubscriptionStatus;
    expiresAt: Timestamp;
    stripeSubscriptionId: string;
    userId: UserId;
    stripeCustomerId: string;
    razorpayOrderId?: string;
    renewalDate: Timestamp;
    startDate: Timestamp;
}
export interface QuizQuestion {
    id: bigint;
    correctOptionId: bigint;
    question: string;
    options: Array<QuizOption>;
}
export interface PaymentRecord {
    status: string;
    userId: UserId;
    plan: string;
    orderId: string;
    paymentId: string;
    timestamp: Timestamp;
    userIdText: string;
    amount: bigint;
}
export interface LoginEvent {
    userId: UserId;
    timestamp: Timestamp;
    userIdText: string;
}
export interface SubscriptionStats {
    recentSignups: bigint;
    totalPayments: bigint;
    subscribedUsers: bigint;
    totalUsers: bigint;
    totalRevenue: bigint;
    activeSubscriptions: bigint;
}
export interface UserProgress {
    lastQuizScore?: bigint;
    userId: UserId;
    streakDays: bigint;
    moduleProgress: Array<ModuleProgress>;
    lastQuizAttemptedAt?: Timestamp;
    totalLearningHours: bigint;
}
export type RazorpayOrderResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface AdminUserView {
    lastLoginAt: Timestamp;
    userId: UserId;
    lastActiveAt: Timestamp;
    subscriptionPlan: string;
    coursesCompleted: bigint;
    loginCount: bigint;
    subscriptionStatus: string;
    signupAt: Timestamp;
    userIdText: string;
    totalProgress: number;
}
export interface CertificateView {
    id: string;
    verificationCode: string;
    userId: UserId;
    issuedAt: Timestamp;
    courseName: string;
    courseId: string;
}
export type UserId = Principal;
export interface Lesson {
    title: string;
    description: string;
    durationMinutes: bigint;
}
export interface QuizAttempt {
    userId: UserId;
    score: bigint;
    totalQuestions: bigint;
    attemptedAt: Timestamp;
}
export interface Term {
    id: bigint;
    term: string;
    example: string;
    category: GlossaryCategory;
    definition: string;
}
export interface CapstoneSubscriptionView {
    razorpayPaymentId?: string;
    activated: boolean;
    activatedAt: Timestamp;
    userId: UserId;
    razorpayOrderId?: string;
}
export interface QuizOption {
    id: bigint;
    text: string;
}
export interface CourseCompletion {
    completedAt: Timestamp;
    userId: UserId;
    certificateId: string;
    userIdText: string;
    courseId: string;
}
export interface ModuleProgress {
    moduleId: bigint;
    completedAt?: Timestamp;
    completed: boolean;
}
export interface ITModule {
    id: bigint;
    title: string;
    difficulty: string;
    description: string;
    lessons: Array<Lesson>;
    isComingSoon: boolean;
    topics: Array<string>;
    estimatedHours: bigint;
    category: ModuleCategory;
    estimatedMinutes: bigint;
}
export enum GlossaryCategory {
    aiml = "aiml",
    cloud = "cloud",
    networking = "networking",
    hardware = "hardware",
    itSupport = "itSupport",
    cybersecurity = "cybersecurity",
    software = "software",
    general = "general"
}
export enum ModuleCategory {
    dsa = "dsa",
    sql = "sql",
    aiml = "aiml",
    java = "java",
    cloud = "cloud",
    mncplatforms = "mncplatforms",
    htmlcss = "htmlcss",
    capstonePproject = "capstonePproject",
    shellscripting = "shellscripting",
    networking = "networking",
    trending = "trending",
    devops = "devops",
    hardware = "hardware",
    excel = "excel",
    corporateskills = "corporateskills",
    itSupport = "itSupport",
    cybersecurity = "cybersecurity",
    software = "software",
    etltools = "etltools",
    cloudaws = "cloudaws",
    presentation = "presentation",
    python = "python",
    corporateWorld = "corporateWorld",
    machinelearning = "machinelearning",
    github = "github",
    itfundamentals = "itfundamentals"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    inactive = "inactive"
}
export interface backendInterface {
    activateCapstoneWithRazorpay(orderId: string, paymentId: string): Promise<boolean>;
    activateSubscriptionWithRazorpay(orderId: string, paymentId: string): Promise<boolean>;
    canAccessCapstone(): Promise<boolean>;
    canAccessLesson(lessonIndex: bigint): Promise<boolean>;
    canAccessModule(moduleIndex: bigint): Promise<boolean>;
    checkSubscription(): Promise<SubscriptionView | null>;
    createCapstoneOrder(): Promise<RazorpayOrderResult>;
    createRazorpayOrder(): Promise<RazorpayOrderResult>;
    getAllUsersAdmin(): Promise<Array<AdminUserView>>;
    getCapstoneSubscription(): Promise<CapstoneSubscriptionView | null>;
    getCertificate(id: string): Promise<CertificateView | null>;
    getCourseCompletions(): Promise<Array<CourseCompletion>>;
    getLoginEvents(): Promise<Array<LoginEvent>>;
    getModule(moduleId: bigint): Promise<ITModule | null>;
    getMyCertificates(): Promise<Array<CertificateView>>;
    getMyProgress(): Promise<UserProgress>;
    getMyQuizAttempt(): Promise<QuizAttempt | null>;
    getPaymentRecords(): Promise<Array<PaymentRecord>>;
    getSubscriptionStatsAdmin(): Promise<SubscriptionStats>;
    getTerm(termId: bigint): Promise<Term | null>;
    getTermsByCategory(category: GlossaryCategory): Promise<Array<Term>>;
    getUserProgressAdmin(userId: UserId): Promise<UserProgress | null>;
    handleStripeWebhook(payload: StripeWebhookPayload): Promise<boolean>;
    linkStripeCustomer(stripeCustomerId: string): Promise<void>;
    listGlossaryTerms(): Promise<Array<Term>>;
    listModules(): Promise<Array<ITModule>>;
    listQuizQuestions(): Promise<Array<QuizQuestion>>;
    listSubscribers(): Promise<Array<SubscriptionView>>;
    markCourseComplete(courseId: string, courseName: string): Promise<CertificateView>;
    markModuleCompleted(moduleId: bigint): Promise<void>;
    recordLoginEvent(): Promise<void>;
    searchGlossary(searchText: string): Promise<Array<Term>>;
    setOwner(): Promise<void>;
    setRazorpayKeys(keyId: string, keySecret: string): Promise<boolean>;
    submitQuizAttempt(answers: Array<[bigint, bigint]>): Promise<QuizAttempt>;
    updateLearningHours(hours: bigint): Promise<void>;
}
import type { CapstoneSubscriptionView as _CapstoneSubscriptionView, CertificateView as _CertificateView, GlossaryCategory as _GlossaryCategory, ITModule as _ITModule, Lesson as _Lesson, ModuleCategory as _ModuleCategory, ModuleProgress as _ModuleProgress, QuizAttempt as _QuizAttempt, RazorpayOrderResult as _RazorpayOrderResult, StripeWebhookPayload as _StripeWebhookPayload, SubscriptionStatus as _SubscriptionStatus, SubscriptionView as _SubscriptionView, Term as _Term, Timestamp as _Timestamp, UserId as _UserId, UserProgress as _UserProgress } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async activateCapstoneWithRazorpay(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.activateCapstoneWithRazorpay(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateCapstoneWithRazorpay(arg0, arg1);
            return result;
        }
    }
    async activateSubscriptionWithRazorpay(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.activateSubscriptionWithRazorpay(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateSubscriptionWithRazorpay(arg0, arg1);
            return result;
        }
    }
    async canAccessCapstone(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canAccessCapstone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canAccessCapstone();
            return result;
        }
    }
    async canAccessLesson(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canAccessLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canAccessLesson(arg0);
            return result;
        }
    }
    async canAccessModule(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canAccessModule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canAccessModule(arg0);
            return result;
        }
    }
    async checkSubscription(): Promise<SubscriptionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSubscription();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSubscription();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCapstoneOrder(): Promise<RazorpayOrderResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createCapstoneOrder();
                return from_candid_RazorpayOrderResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCapstoneOrder();
            return from_candid_RazorpayOrderResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRazorpayOrder(): Promise<RazorpayOrderResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayOrder();
                return from_candid_RazorpayOrderResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayOrder();
            return from_candid_RazorpayOrderResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersAdmin(): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersAdmin();
            return result;
        }
    }
    async getCapstoneSubscription(): Promise<CapstoneSubscriptionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapstoneSubscription();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapstoneSubscription();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificate(arg0: string): Promise<CertificateView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificate(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificate(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseCompletions(): Promise<Array<CourseCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseCompletions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseCompletions();
            return result;
        }
    }
    async getLoginEvents(): Promise<Array<LoginEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoginEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoginEvents();
            return result;
        }
    }
    async getModule(arg0: bigint): Promise<ITModule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModule(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModule(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCertificates(): Promise<Array<CertificateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCertificates();
            return result;
        }
    }
    async getMyProgress(): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress();
                return from_candid_UserProgress_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress();
            return from_candid_UserProgress_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQuizAttempt(): Promise<QuizAttempt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizAttempt();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizAttempt();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentRecords(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRecords();
            return result;
        }
    }
    async getSubscriptionStatsAdmin(): Promise<SubscriptionStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionStatsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionStatsAdmin();
            return result;
        }
    }
    async getTerm(arg0: bigint): Promise<Term | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTerm(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTerm(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTermsByCategory(arg0: GlossaryCategory): Promise<Array<Term>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTermsByCategory(to_candid_GlossaryCategory_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTermsByCategory(to_candid_GlossaryCategory_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProgressAdmin(arg0: UserId): Promise<UserProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgressAdmin(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgressAdmin(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleStripeWebhook(arg0: StripeWebhookPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.handleStripeWebhook(to_candid_StripeWebhookPayload_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleStripeWebhook(to_candid_StripeWebhookPayload_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async linkStripeCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkStripeCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkStripeCustomer(arg0);
            return result;
        }
    }
    async listGlossaryTerms(): Promise<Array<Term>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGlossaryTerms();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGlossaryTerms();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listModules(): Promise<Array<ITModule>> {
        if (this.processError) {
            try {
                const result = await this.actor.listModules();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listModules();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuizQuestions(): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuizQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuizQuestions();
            return result;
        }
    }
    async listSubscribers(): Promise<Array<SubscriptionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubscribers();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubscribers();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async markCourseComplete(arg0: string, arg1: string): Promise<CertificateView> {
        if (this.processError) {
            try {
                const result = await this.actor.markCourseComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCourseComplete(arg0, arg1);
            return result;
        }
    }
    async markModuleCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markModuleCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markModuleCompleted(arg0);
            return result;
        }
    }
    async recordLoginEvent(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordLoginEvent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordLoginEvent();
            return result;
        }
    }
    async searchGlossary(arg0: string): Promise<Array<Term>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGlossary(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGlossary(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async setOwner(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOwner();
            return result;
        }
    }
    async setRazorpayKeys(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setRazorpayKeys(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRazorpayKeys(arg0, arg1);
            return result;
        }
    }
    async submitQuizAttempt(arg0: Array<[bigint, bigint]>): Promise<QuizAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAttempt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAttempt(arg0);
            return result;
        }
    }
    async updateLearningHours(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLearningHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLearningHours(arg0);
            return result;
        }
    }
}
function from_candid_CapstoneSubscriptionView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CapstoneSubscriptionView): CapstoneSubscriptionView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_GlossaryCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlossaryCategory): GlossaryCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ITModule_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ITModule): ITModule {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ModuleCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleCategory): ModuleCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ModuleProgress_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleProgress): ModuleProgress {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RazorpayOrderResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RazorpayOrderResult): RazorpayOrderResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionView): SubscriptionView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Term_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Term): Term {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProgress_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionView]): SubscriptionView | null {
    return value.length === 0 ? null : from_candid_SubscriptionView_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CertificateView]): CertificateView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ITModule]): ITModule | null {
    return value.length === 0 ? null : from_candid_ITModule_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizAttempt]): QuizAttempt | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Term]): Term | null {
    return value.length === 0 ? null : from_candid_Term_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProgress]): UserProgress | null {
    return value.length === 0 ? null : from_candid_UserProgress_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CapstoneSubscriptionView]): CapstoneSubscriptionView | null {
    return value.length === 0 ? null : from_candid_CapstoneSubscriptionView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    razorpayPaymentId: [] | [string];
    activated: boolean;
    activatedAt: _Timestamp;
    userId: _UserId;
    razorpayOrderId: [] | [string];
}): {
    razorpayPaymentId?: string;
    activated: boolean;
    activatedAt: Timestamp;
    userId: UserId;
    razorpayOrderId?: string;
} {
    return {
        razorpayPaymentId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.razorpayPaymentId)),
        activated: value.activated,
        activatedAt: value.activatedAt,
        userId: value.userId,
        razorpayOrderId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.razorpayOrderId))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    difficulty: string;
    description: string;
    lessons: Array<_Lesson>;
    isComingSoon: boolean;
    topics: Array<string>;
    estimatedHours: bigint;
    category: _ModuleCategory;
    estimatedMinutes: bigint;
}): {
    id: bigint;
    title: string;
    difficulty: string;
    description: string;
    lessons: Array<Lesson>;
    isComingSoon: boolean;
    topics: Array<string>;
    estimatedHours: bigint;
    category: ModuleCategory;
    estimatedMinutes: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        difficulty: value.difficulty,
        description: value.description,
        lessons: value.lessons,
        isComingSoon: value.isComingSoon,
        topics: value.topics,
        estimatedHours: value.estimatedHours,
        category: from_candid_ModuleCategory_n16(_uploadFile, _downloadFile, value.category),
        estimatedMinutes: value.estimatedMinutes
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastQuizScore: [] | [bigint];
    userId: _UserId;
    streakDays: bigint;
    moduleProgress: Array<_ModuleProgress>;
    lastQuizAttemptedAt: [] | [_Timestamp];
    totalLearningHours: bigint;
}): {
    lastQuizScore?: bigint;
    userId: UserId;
    streakDays: bigint;
    moduleProgress: Array<ModuleProgress>;
    lastQuizAttemptedAt?: Timestamp;
    totalLearningHours: bigint;
} {
    return {
        lastQuizScore: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.lastQuizScore)),
        userId: value.userId,
        streakDays: value.streakDays,
        moduleProgress: from_candid_vec_n21(_uploadFile, _downloadFile, value.moduleProgress),
        lastQuizAttemptedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.lastQuizAttemptedAt)),
        totalLearningHours: value.totalLearningHours
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleId: bigint;
    completedAt: [] | [_Timestamp];
    completed: boolean;
}): {
    moduleId: bigint;
    completedAt?: Timestamp;
    completed: boolean;
} {
    return {
        moduleId: value.moduleId,
        completedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.completedAt)),
        completed: value.completed
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    term: string;
    example: string;
    category: _GlossaryCategory;
    definition: string;
}): {
    id: bigint;
    term: string;
    example: string;
    category: GlossaryCategory;
    definition: string;
} {
    return {
        id: value.id,
        term: value.term,
        example: value.example,
        category: from_candid_GlossaryCategory_n29(_uploadFile, _downloadFile, value.category),
        definition: value.definition
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    razorpayPaymentId: [] | [string];
    status: _SubscriptionStatus;
    expiresAt: _Timestamp;
    stripeSubscriptionId: string;
    userId: _UserId;
    stripeCustomerId: string;
    razorpayOrderId: [] | [string];
    renewalDate: _Timestamp;
    startDate: _Timestamp;
}): {
    razorpayPaymentId?: string;
    status: SubscriptionStatus;
    expiresAt: Timestamp;
    stripeSubscriptionId: string;
    userId: UserId;
    stripeCustomerId: string;
    razorpayOrderId?: string;
    renewalDate: Timestamp;
    startDate: Timestamp;
} {
    return {
        razorpayPaymentId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.razorpayPaymentId)),
        status: from_candid_SubscriptionStatus_n5(_uploadFile, _downloadFile, value.status),
        expiresAt: value.expiresAt,
        stripeSubscriptionId: value.stripeSubscriptionId,
        userId: value.userId,
        stripeCustomerId: value.stripeCustomerId,
        razorpayOrderId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.razorpayOrderId)),
        renewalDate: value.renewalDate,
        startDate: value.startDate
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dsa: null;
} | {
    sql: null;
} | {
    aiml: null;
} | {
    java: null;
} | {
    cloud: null;
} | {
    mncplatforms: null;
} | {
    htmlcss: null;
} | {
    capstonePproject: null;
} | {
    shellscripting: null;
} | {
    networking: null;
} | {
    trending: null;
} | {
    devops: null;
} | {
    hardware: null;
} | {
    excel: null;
} | {
    corporateskills: null;
} | {
    itSupport: null;
} | {
    cybersecurity: null;
} | {
    software: null;
} | {
    etltools: null;
} | {
    cloudaws: null;
} | {
    presentation: null;
} | {
    python: null;
} | {
    corporateWorld: null;
} | {
    machinelearning: null;
} | {
    github: null;
} | {
    itfundamentals: null;
}): ModuleCategory {
    return "dsa" in value ? ModuleCategory.dsa : "sql" in value ? ModuleCategory.sql : "aiml" in value ? ModuleCategory.aiml : "java" in value ? ModuleCategory.java : "cloud" in value ? ModuleCategory.cloud : "mncplatforms" in value ? ModuleCategory.mncplatforms : "htmlcss" in value ? ModuleCategory.htmlcss : "capstonePproject" in value ? ModuleCategory.capstonePproject : "shellscripting" in value ? ModuleCategory.shellscripting : "networking" in value ? ModuleCategory.networking : "trending" in value ? ModuleCategory.trending : "devops" in value ? ModuleCategory.devops : "hardware" in value ? ModuleCategory.hardware : "excel" in value ? ModuleCategory.excel : "corporateskills" in value ? ModuleCategory.corporateskills : "itSupport" in value ? ModuleCategory.itSupport : "cybersecurity" in value ? ModuleCategory.cybersecurity : "software" in value ? ModuleCategory.software : "etltools" in value ? ModuleCategory.etltools : "cloudaws" in value ? ModuleCategory.cloudaws : "presentation" in value ? ModuleCategory.presentation : "python" in value ? ModuleCategory.python : "corporateWorld" in value ? ModuleCategory.corporateWorld : "machinelearning" in value ? ModuleCategory.machinelearning : "github" in value ? ModuleCategory.github : "itfundamentals" in value ? ModuleCategory.itfundamentals : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiml: null;
} | {
    cloud: null;
} | {
    networking: null;
} | {
    hardware: null;
} | {
    itSupport: null;
} | {
    cybersecurity: null;
} | {
    software: null;
} | {
    general: null;
}): GlossaryCategory {
    return "aiml" in value ? GlossaryCategory.aiml : "cloud" in value ? GlossaryCategory.cloud : "networking" in value ? GlossaryCategory.networking : "hardware" in value ? GlossaryCategory.hardware : "itSupport" in value ? GlossaryCategory.itSupport : "cybersecurity" in value ? GlossaryCategory.cybersecurity : "software" in value ? GlossaryCategory.software : "general" in value ? GlossaryCategory.general : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    inactive: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "inactive" in value ? SubscriptionStatus.inactive : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModuleProgress>): Array<ModuleProgress> {
    return value.map((x)=>from_candid_ModuleProgress_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Term>): Array<Term> {
    return value.map((x)=>from_candid_Term_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ITModule>): Array<ITModule> {
    return value.map((x)=>from_candid_ITModule_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubscriptionView>): Array<SubscriptionView> {
    return value.map((x)=>from_candid_SubscriptionView_n2(_uploadFile, _downloadFile, x));
}
function to_candid_GlossaryCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GlossaryCategory): _GlossaryCategory {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_StripeWebhookPayload_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StripeWebhookPayload): _StripeWebhookPayload {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripeSubscriptionId: string;
    userId?: UserId;
    stripeCustomerId: string;
    eventType: string;
}): {
    stripeSubscriptionId: string;
    userId: [] | [_UserId];
    stripeCustomerId: string;
    eventType: string;
} {
    return {
        stripeSubscriptionId: value.stripeSubscriptionId,
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        stripeCustomerId: value.stripeCustomerId,
        eventType: value.eventType
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GlossaryCategory): {
    aiml: null;
} | {
    cloud: null;
} | {
    networking: null;
} | {
    hardware: null;
} | {
    itSupport: null;
} | {
    cybersecurity: null;
} | {
    software: null;
} | {
    general: null;
} {
    return value == GlossaryCategory.aiml ? {
        aiml: null
    } : value == GlossaryCategory.cloud ? {
        cloud: null
    } : value == GlossaryCategory.networking ? {
        networking: null
    } : value == GlossaryCategory.hardware ? {
        hardware: null
    } : value == GlossaryCategory.itSupport ? {
        itSupport: null
    } : value == GlossaryCategory.cybersecurity ? {
        cybersecurity: null
    } : value == GlossaryCategory.software ? {
        software: null
    } : value == GlossaryCategory.general ? {
        general: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
